
package com.addressbook.vaadin.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JpaContactUtils", targetNamespace = "http://ws.jpa.contact.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface JpaContactUtils {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://ws.jpa.contact.com/JpaContactUtils/addContactToDatabaseRequest", output = "http://ws.jpa.contact.com/JpaContactUtils/addContactToDatabaseResponse")
    public void addContactToDatabase(
        @WebParam(name = "arg0", partName = "arg0")
        Contact arg0);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg11
     * @param arg12
     * @param arg10
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     */
    @WebMethod
    @Action(input = "http://ws.jpa.contact.com/JpaContactUtils/updateContactToDatabaseRequest", output = "http://ws.jpa.contact.com/JpaContactUtils/updateContactToDatabaseResponse")
    public void updateContactToDatabase(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7,
        @WebParam(name = "arg8", partName = "arg8")
        String arg8,
        @WebParam(name = "arg9", partName = "arg9")
        String arg9,
        @WebParam(name = "arg10", partName = "arg10")
        String arg10,
        @WebParam(name = "arg11", partName = "arg11")
        String arg11,
        @WebParam(name = "arg12", partName = "arg12")
        String arg12);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://ws.jpa.contact.com/JpaContactUtils/deleteContactToDatabaseRequest", output = "http://ws.jpa.contact.com/JpaContactUtils/deleteContactToDatabaseResponse")
    public void deleteContactToDatabase(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

}
