
package com.addressbook.vaadin.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "JpaContactUtilsImplService", targetNamespace = "http://ws.jpa.contact.com/", wsdlLocation = "http://localhost:9999/ws/jpa/contact?wsdl")
public class JpaContactUtilsImplService
    extends Service
{

    private final static URL JPACONTACTUTILSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException JPACONTACTUTILSIMPLSERVICE_EXCEPTION;
    private final static QName JPACONTACTUTILSIMPLSERVICE_QNAME = new QName("http://ws.jpa.contact.com/", "JpaContactUtilsImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/ws/jpa/contact?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JPACONTACTUTILSIMPLSERVICE_WSDL_LOCATION = url;
        JPACONTACTUTILSIMPLSERVICE_EXCEPTION = e;
    }

    public JpaContactUtilsImplService() {
        super(__getWsdlLocation(), JPACONTACTUTILSIMPLSERVICE_QNAME);
    }

    public JpaContactUtilsImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), JPACONTACTUTILSIMPLSERVICE_QNAME, features);
    }

    public JpaContactUtilsImplService(URL wsdlLocation) {
        super(wsdlLocation, JPACONTACTUTILSIMPLSERVICE_QNAME);
    }

    public JpaContactUtilsImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JPACONTACTUTILSIMPLSERVICE_QNAME, features);
    }

    public JpaContactUtilsImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JpaContactUtilsImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns JpaContactUtils
     */
    @WebEndpoint(name = "JpaContactUtilsImplPort")
    public JpaContactUtils getJpaContactUtilsImplPort() {
        return super.getPort(new QName("http://ws.jpa.contact.com/", "JpaContactUtilsImplPort"), JpaContactUtils.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JpaContactUtils
     */
    @WebEndpoint(name = "JpaContactUtilsImplPort")
    public JpaContactUtils getJpaContactUtilsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.jpa.contact.com/", "JpaContactUtilsImplPort"), JpaContactUtils.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JPACONTACTUTILSIMPLSERVICE_EXCEPTION!= null) {
            throw JPACONTACTUTILSIMPLSERVICE_EXCEPTION;
        }
        return JPACONTACTUTILSIMPLSERVICE_WSDL_LOCATION;
    }

}
